on:
  push:
    branches:
      - master

name: R-CMD-check

jobs:
  ubuntu-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
            r-version: "3.4"
      - name: System dependencies
        run: sudo apt-get install libcurl4-openssl-dev libpoppler-cpp-dev libmagick++-dev
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
