name: R-CMD-check

on:
  pull_request:
    branches:
      - master

name: R-CMD-check
author: Matias Barrientos G

jobs:
  check:
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
            r-version: "3.4"

      - name: System dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install libcurl4-openssl-dev libpoppler-cpp-dev libmagick++-dev pandoc pandoc-citeproc
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install poppler libmagic openssl pandoc pandoc-citeproc imagemagick@6
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        shell: bash

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "stringi", "Rcpp"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), check_dir = "check")
        shell: Rscript {0}
